### ISSUE TITLE
提取vant-app组件无效

### ISSUE THREAD

**Issue by xn1254** [mcc108/gulp-mp-npm#11]
![image](https://user-images.githubusercontent.com/26221039/133056446-dec41a3e-7355-4ec7-8499-82aa44626d9d.png)
![image](https://user-images.githubusercontent.com/26221039/133056484-c591c267-4419-4bbd-a5a1-178598d37fe2.png)
在提取vant-app组件的时候无效

**Comment by mcc108** [comment]
这个使用的地址需要去掉dist哈，例如`@vant/weapp/steps/index`

**Comment by xn1254** [comment]
好的，谢谢

**Comment by xn1254** [comment]
![image](https://user-images.githubusercontent.com/26221039/133059576-54090a3f-d3be-412d-a6b3-e815ab629000.png)
但是还有个问题，像这种组件内部的依赖没有提取出来

**Comment by mcc108** [comment]
目前暂没支持解析wxs的依赖，但有其他办法能解决，可以看一看这个回复，像这样配置：
https://github.com/mcc108/gulp-mp-npm/issues/8#issuecomment-846869347

**Comment by xn1254** [comment]
好的
