### ISSUE TITLE
导入第三方包报错

### ISSUE THREAD

**Issue by cNelf** [mcc108/gulp-mp-npm#8]
好像没有办法分析出node_modules文件内部的依赖，导致引入vant后报依赖丢失错误。
使用fullExtract: ['@vant/weapp']可以解决，可是会把所有组件都打包进去，请问下有没有更好的解决方案呢？

**Comment by mcc108** [comment]
vant里用到的wxml用到的.wxs文件目前是暂时没能分析并导出，这也会导致依赖的丢失。
临时的用法是使用fullExtract，它可以指定到具体的文件路径，
比如丢失wxs依赖可以尝试使用`fullExtract: ['@vant/weapp/wxs']`，这样会只这个文件夹内的内容全量提取出来

**Comment by cNelf** [comment]
@mcc108 可以实现，thx~  : )
